version: '3'

services:
  db1:
    image: postgres:10
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'

  db2:
    image: postgres:10
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
